"""initial_schema

Revision ID: 8c005ee89373
Revises: 
Create Date: 2026-06-02 12:27:27.969475
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c005ee89373'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_info',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('ruc', sa.String(length=13), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('commercial_name', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('dispatch_types',
    sa.Column('dispatch_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('requires_customer', sa.Boolean(), nullable=False),
    sa.Column('affects_cash', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('dispatch_type_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('emission_points',
    sa.Column('emission_point_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('establishment', sa.String(length=3), nullable=False),
    sa.Column('emission_point', sa.String(length=3), nullable=False),
    sa.Column('current_sequential', sa.BigInteger(), nullable=False),
    sa.Column('sequential_start', sa.BigInteger(), nullable=False),
    sa.Column('sequential_end', sa.BigInteger(), nullable=False),
    sa.Column('doc_type', sa.String(length=20), nullable=False),
    sa.Column('authorization_number', sa.String(length=50), nullable=True),
    sa.Column('authorization_date', sa.Date(), nullable=True),
    sa.Column('authorization_expiry', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('emission_point_id')
    )
    op.create_table('payment_methods',
    sa.Column('payment_method_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('requires_reference', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('payment_method_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('price_lists',
    sa.Column('price_list_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('price_list_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('product_categories',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_fuel', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('category_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('permissions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('system_config',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tax_types',
    sa.Column('tax_type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('tax_type_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('dispensers',
    sa.Column('dispenser_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emission_point_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('fusion_pump_id', sa.Integer(), nullable=False),
    sa.Column('printer_ip', sa.String(length=45), nullable=True),
    sa.Column('printer_port', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['emission_point_id'], ['emission_points.emission_point_id'], ),
    sa.PrimaryKeyConstraint('dispenser_id')
    )
    op.create_table('persons',
    sa.Column('person_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_type', sa.String(length=5), nullable=False),
    sa.Column('id_number', sa.String(length=13), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('price_list_id', sa.Integer(), nullable=True),
    sa.Column('yalobox_wallet', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.price_list_id'], ),
    sa.PrimaryKeyConstraint('person_id')
    )
    op.create_table('products',
    sa.Column('product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('tax_type_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.category_id'], ),
    sa.ForeignKeyConstraint(['tax_type_id'], ['tax_types.tax_type_id'], ),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('pin_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('accounting_cash_code', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('credit_contracts',
    sa.Column('contract_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_code', sa.String(length=30), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('contract_date', sa.Date(), nullable=False),
    sa.Column('cupo', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('contract_type', sa.String(length=15), nullable=False),
    sa.Column('sercop_type', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("contract_type IN ('INDEFINIDO', 'NO_INDEFINIDO')", name='ck_credit_contracts_type'),
    sa.CheckConstraint("sercop_type IN ('INFIMA_CUANTIA', 'ADJUDICACION', 'CONTRATACION_DIRECTA', 'NO_DEFINIDO')", name='ck_credit_contracts_sercop'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.person_id'], ),
    sa.PrimaryKeyConstraint('contract_id'),
    sa.UniqueConstraint('contract_code')
    )
    op.create_table('grades',
    sa.Column('grade_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('grade_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('hoses',
    sa.Column('hose_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dispenser_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.CHAR(length=1), nullable=False),
    sa.Column('fusion_pump_id', sa.Integer(), nullable=False),
    sa.Column('fusion_hose_id', sa.Integer(), nullable=False),
    sa.Column('grade_id', sa.String(length=20), nullable=False),
    sa.CheckConstraint("side IN ('A', 'B')", name='ck_hoses_side'),
    sa.ForeignKeyConstraint(['dispenser_id'], ['dispensers.dispenser_id'], ),
    sa.PrimaryKeyConstraint('hose_id')
    )
    op.create_table('price_list_items',
    sa.Column('price_list_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('price_list_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.price_list_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('price_list_item_id'),
    sa.UniqueConstraint('price_list_id', 'product_id', name='uq_price_list_product')
    )
    op.create_table('shifts',
    sa.Column('shift_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('opening_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('closing_cash', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accounting_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.CheckConstraint("status IN ('OPEN', 'CLOSED')", name='ck_shifts_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('shift_id')
    )
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plate', sa.String(length=10), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('price_list_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.person_id'], ),
    sa.ForeignKeyConstraint(['price_list_id'], ['price_lists.price_list_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('plate')
    )
    op.create_table('cash_movements',
    sa.Column('movement_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observation', sa.String(length=300), nullable=True),
    sa.Column('running_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.Column('related_user_name', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('INCOME', 'EXPENSE', 'SAFE_DROP', 'TRANSFER_OUT')", name='ck_cash_movements_type'),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], ),
    sa.PrimaryKeyConstraint('movement_id')
    )
    op.create_table('credit_contract_products',
    sa.Column('contract_product_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['credit_contracts.contract_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('contract_product_id'),
    sa.UniqueConstraint('contract_id', 'product_id', name='uq_contract_product')
    )
    op.create_table('credit_contract_vehicles',
    sa.Column('contract_vehicle_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['credit_contracts.contract_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('contract_vehicle_id'),
    sa.UniqueConstraint('contract_id', 'vehicle_id', name='uq_contract_vehicle')
    )
    op.create_table('dispatches',
    sa.Column('dispatch_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=30), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=False),
    sa.Column('dispenser_id', sa.Integer(), nullable=False),
    sa.Column('emission_point_id', sa.Integer(), nullable=True),
    sa.Column('sequential_number', sa.String(length=20), nullable=True),
    sa.Column('dispatch_type_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('credit_contract_id', sa.Integer(), nullable=True),
    sa.Column('credit_status', sa.String(length=20), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('authorized_by', sa.String(length=150), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.CheckConstraint("credit_status IS NULL OR credit_status IN ('PENDING_INVOICE', 'INVOICED')", name='ck_dispatches_credit_status'),
    sa.CheckConstraint("status IN ('AUTHORIZED', 'COMPLETED', 'COLLECTED', 'CANCELLED')", name='ck_dispatches_status'),
    sa.ForeignKeyConstraint(['credit_contract_id'], ['credit_contracts.contract_id'], ),
    sa.ForeignKeyConstraint(['dispatch_type_id'], ['dispatch_types.dispatch_type_id'], ),
    sa.ForeignKeyConstraint(['dispenser_id'], ['dispensers.dispenser_id'], ),
    sa.ForeignKeyConstraint(['emission_point_id'], ['emission_points.emission_point_id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.person_id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.shift_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('dispatch_id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_table('transfers',
    sa.Column('transfer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_shift_id', sa.Integer(), nullable=False),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_name', sa.String(length=150), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('observation', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_shift_id'], ['shifts.shift_id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('transfer_id')
    )
    op.create_table('dispatch_details',
    sa.Column('detail_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.dispatch_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
    sa.PrimaryKeyConstraint('detail_id')
    )
    op.create_table('dispatch_payments',
    sa.Column('payment_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dispatch_id', sa.Integer(), nullable=False),
    sa.Column('payment_method_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('reference_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dispatch_id'], ['dispatches.dispatch_id'], ),
    sa.ForeignKeyConstraint(['payment_method_id'], ['payment_methods.payment_method_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispatch_payments')
    op.drop_table('dispatch_details')
    op.drop_table('transfers')
    op.drop_table('dispatches')
    op.drop_table('credit_contract_vehicles')
    op.drop_table('credit_contract_products')
    op.drop_table('cash_movements')
    op.drop_table('vehicles')
    op.drop_table('shifts')
    op.drop_table('price_list_items')
    op.drop_table('hoses')
    op.drop_table('grades')
    op.drop_table('credit_contracts')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('persons')
    op.drop_table('dispensers')
    op.drop_table('tax_types')
    op.drop_table('system_config')
    op.drop_table('roles')
    op.drop_table('product_categories')
    op.drop_table('price_lists')
    op.drop_table('payment_methods')
    op.drop_table('emission_points')
    op.drop_table('dispatch_types')
    op.drop_table('company_info')
    # ### end Alembic commands ###
